[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self' api.aladhan.com; script-src 'self' 'unsafe-inline'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"